const FETCH_DATA_PROJECT = 'FETCH_DATA_PROJECT';
const FIND_BY_ID_PROJECT = 'FIND_BY_ID_PROJECT';
const FETCH_DATA_COUNSELOR = 'FETCH_DATA_COUNSELOR';
const FIND_BY_ID_COUNSELOR = 'FIND_BY_ID_COUNSELOR';
const FETCH_DATA_NEWS = 'FETCH_DATA_NEWS';
const FIND_BY_ID_NEWS = 'FIND_BY_ID_NEWS';

export const actionType = {
  FETCH_DATA_PROJECT,
  FIND_BY_ID_PROJECT,
  FETCH_DATA_COUNSELOR,
  FIND_BY_ID_COUNSELOR,
  FETCH_DATA_NEWS,
  FIND_BY_ID_NEWS,
};
