const FETCH_DATA_PROJECT = 'FETCH_DATA_PROJECT';
const FIND_BY_ID_PROJECT = 'FIND_BY_ID_PROJECT';
const FETCH_DATA_COUNSELOR = 'FETCH_DATA_COUNSELOR';
const FIND_BY_ID_COUNSELOR = 'FIND_BY_ID_COUNSELOR';

export const actionType = {
  FETCH_DATA_PROJECT,
  FIND_BY_ID_PROJECT,
  FETCH_DATA_COUNSELOR,
  FIND_BY_ID_COUNSELOR,
};
